#!/bin/bash

echo "HTTP/1.1 200 OK"
echo "Date: $(date)"
echo "Connection: close"
echo "Server: my_little_web_server/0.1"
echo "Refresh: 2; url=http://localhost:$1"
echo "Content-Type: text/html"
echo ""
echo "<html>"
echo "<head>"
echo " <title>Loading</title>"
echo "</head>"
echo "<body>"
echo "Page Loading...."
echo "</body>"
echo "<html>"
